name: signals_lint
description: linter and developer tool for signals
version: 5.0.0
repository: https://github.com/rodydavis/signals.dart
homepage: https://dartsignals.dev/
documentation: https://dartsignals.dev/
topics:
  - state-management
  - state
  - signals
  - rx
  - linter

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^6.9.0
  analyzer_plugin: ^0.11.3
  collection: ^1.19.0
  custom_lint_builder: ^0.6.5
  build: ^2.4.1
  stream_transform: ^2.1.0
  signals:
    path: ../signals

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.8
